---
# Handler for restarting ssh service
- name: restart ssh
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
    daemon_reload: yes

# Handler for restarting fail2ban
- name: restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
    daemon_reload: yes

# Handler for reloading sysctl
- name: reload sysctl
  ansible.builtin.sysctl:
    state: reloaded